runtime: nodejs
env: flex

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

env_variables:
  GCLOUD_PROJECT: cproject-158114

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

manual_scaling:
  instances: 1

# [START network]
# This ensures clients will be able to connect via websockets to any instance of
# this app using websockets
network:
  forwarded_ports:
  - 65080
  instance_tag: websocket
# [END network]
