runtime: nodejs
env: flex

# Temporary setting to keep gcloud from uploading node_modules
skip_files:
 - ^node_modules$

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
